backend:
  name: github
  repo: USEPA/capd-test-docs
  branch: test-decap
  base_url: https://usepa.github.io/capd-test-docs
  auth_endpoint: /admin/external/auth/github
  client_id: Ov23likqtmFqj6W5lcWe
  preview_context: pages/build
media_folder: "app/public/images/"
public_folder: "/images"
collections:
  - name: "posts" 
    label: "Blog Posts"
    folder: "posts" 
    create: true 
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }